// Code generated by ogen, DO NOT EDIT.

package browserbase

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateContextOperation        OperationName = "CreateContext"
	CreateExtensionOperation      OperationName = "CreateExtension"
	CreateSessionOperation        OperationName = "CreateSession"
	CreateSessionUploadsOperation OperationName = "CreateSessionUploads"
	DeleteExtensionOperation      OperationName = "DeleteExtension"
	GetSessionRecordingOperation  OperationName = "GetSessionRecording"
	ListProjectsOperation         OperationName = "ListProjects"
	ListSessionDownloadsOperation OperationName = "ListSessionDownloads"
	ListSessionLogsOperation      OperationName = "ListSessionLogs"
	ListSessionsOperation         OperationName = "ListSessions"
	ProjectUsageOperation         OperationName = "ProjectUsage"
	RetrieveContextOperation      OperationName = "RetrieveContext"
	RetrieveExtensionOperation    OperationName = "RetrieveExtension"
	RetrieveProjectOperation      OperationName = "RetrieveProject"
	RetrieveSessionOperation      OperationName = "RetrieveSession"
	SessionDebugOperation         OperationName = "SessionDebug"
	UpdateContextOperation        OperationName = "UpdateContext"
	UpdateSessionOperation        OperationName = "UpdateSession"
)
