// Code generated by ogen, DO NOT EDIT.

package browserbase

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// XBBAPIKey provides X_BB_API_Key security value.
	XBBAPIKey(ctx context.Context, operationName OperationName) (XBBAPIKey, error)
}

func (s *Client) securityXBBAPIKey(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.XBBAPIKey(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"XBBAPIKey\"")
	}
	req.Header.Set("X-BB-API-Key", t.APIKey)
	return nil
}
