// Code generated by ogen, DO NOT EDIT.

package browserbase

// CreateSessionUploadsParams is parameters of createSessionUploads operation.
type CreateSessionUploadsParams struct {
	ID string
}

// DeleteExtensionParams is parameters of deleteExtension operation.
type DeleteExtensionParams struct {
	ID string
}

// GetSessionRecordingParams is parameters of getSessionRecording operation.
type GetSessionRecordingParams struct {
	ID string
}

// ListSessionDownloadsParams is parameters of listSessionDownloads operation.
type ListSessionDownloadsParams struct {
	ID string
}

// ListSessionLogsParams is parameters of listSessionLogs operation.
type ListSessionLogsParams struct {
	ID string
}

// ListSessionsParams is parameters of listSessions operation.
type ListSessionsParams struct {
	// Query sessions by user metadata.
	Q      OptString
	Status OptSessionStatus
}

// ProjectUsageParams is parameters of projectUsage operation.
type ProjectUsageParams struct {
	ID string
}

// RetrieveContextParams is parameters of retrieveContext operation.
type RetrieveContextParams struct {
	ID string
}

// RetrieveExtensionParams is parameters of retrieveExtension operation.
type RetrieveExtensionParams struct {
	ID string
}

// RetrieveProjectParams is parameters of retrieveProject operation.
type RetrieveProjectParams struct {
	ID string
}

// RetrieveSessionParams is parameters of retrieveSession operation.
type RetrieveSessionParams struct {
	ID string
}

// SessionDebugParams is parameters of sessionDebug operation.
type SessionDebugParams struct {
	ID string
}

// UpdateContextParams is parameters of updateContext operation.
type UpdateContextParams struct {
	ID string
}

// UpdateSessionParams is parameters of updateSession operation.
type UpdateSessionParams struct {
	ID string
}
